name: Test SWAPI Starship

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Ação para verificar o código
      - name: Checkout code
        uses: actions/checkout@v3  # A versão mais recente do checkout

      # Configura a versão do Node.js para 20
      - name: Setup Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      # Instala as dependências necessárias
      - name: Install dependencies
        run: npm install

      # Garantir permissões de execução, se necessário
      - name: Ensure executable permissions
        run: chmod +x ./path/to/your/script.sh  # Verifique o caminho correto

      # Executa os testes
      - name: Run tests
        run: npm test
